name: Shell Commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script 
        run: |
          node -v
          npm -v
      - name: phython Commands
        run: |
         import platform
         print(platform.processor())
        shell: python
  test-another-shell-command:
    runs-on: windows
    steps:
      - name: list directory
        run: dir
